### ISSUE TITLE
Retention on Firebase

### ISSUE THREAD

**Issue by asaeli** [sagishporer/big-query-queries-for-firebase#1]
Hi, 
I see higher retention on Bigquery Firebase and I wonder why it is so high compared to the data that we get on firebase dashboard

select a.install_date,a.platform app_platform,a.app_id,a.country,version,
                             count(distinct a.app_instance_id) installers,
                             count(distinct case when date_diff(date, install_date, DAY)=0 then a.app_instance_id end) d0,
                             count(distinct case when date_diff(date, install_date, DAY)=1 then a.app_instance_id end) d1,
                             count(distinct case when date_diff(date, install_date, DAY)=2 then a.app_instance_id end) d2, 
                             count(distinct case when date_diff(date, install_date, DAY)=3 then a.app_instance_id end) d3,  
                             count(distinct case when date_diff(date, install_date, DAY)=4 then a.app_instance_id end) d4,          
                             count(distinct case when date_diff(date, install_date, DAY)=5 then a.app_instance_id end) d5,       
                             count(distinct case when date_diff(date, install_date, DAY)=6 then a.app_instance_id end) d6,       
                             count(distinct case when date_diff(date, install_date, DAY)=7 then a.app_instance_id end) d7,       
                             count(distinct case when date_diff(date, install_date, DAY)=8 then a.app_instance_id end) d8,      
                             count(distinct case when date_diff(date, install_date, DAY)=9 then a.app_instance_id end) d9,      
                             count(distinct case when date_diff(date, install_date, DAY)=10 then a.app_instance_id end) d10,    
                             count(distinct case when date_diff(date, install_date, DAY)=11 then a.app_instance_id end) d11,     
                             count(distinct case when date_diff(date, install_date, DAY)=12 then a.app_instance_id end) d12,     
                             count(distinct case when date_diff(date, install_date, DAY)=13 then a.app_instance_id end) d13,     
                             count(distinct case when date_diff(date, install_date, DAY)=14 then a.app_instance_id end) d14,     
                             count(distinct case when date_diff(date, install_date, DAY)=15 then a.app_instance_id end) d15,    
                             count(distinct case when date_diff(date, install_date, DAY)=16 then a.app_instance_id end) d16,    
                             count(distinct case when date_diff(date, install_date, DAY)=17 then a.app_instance_id end) d17,    
                             count(distinct case when date_diff(date, install_date, DAY)=18 then a.app_instance_id end) d18,   
                             count(distinct case when date_diff(date, install_date, DAY)=19 then a.app_instance_id end) d19,   
                             count(distinct case when date_diff(date, install_date, DAY)=20 then a.app_instance_id end) d20,   
                             count(distinct case when date_diff(date, install_date, DAY)=21 then a.app_instance_id end) d21,   
                             count(distinct case when date_diff(date, install_date, DAY)=22 then a.app_instance_id end) d22,  
                             count(distinct case when date_diff(date, install_date, DAY)=23 then a.app_instance_id end) d23,   
                             count(distinct case when date_diff(date, install_date, DAY)=24 then a.app_instance_id end) d24,   
                             count(distinct case when date_diff(date, install_date, DAY)=25 then a.app_instance_id end) d25,    
                             count(distinct case when date_diff(date, install_date, DAY)=26 then a.app_instance_id end) d26,    
                             count(distinct case when date_diff(date, install_date, DAY)=27 then a.app_instance_id end) d27,    
                             count(distinct case when date_diff(date, install_date, DAY)=28 then a.app_instance_id end) d28,    
                             count(distinct case when date_diff(date, install_date, DAY)=29 then a.app_instance_id end) d29,     
                             count(distinct case when date_diff(date, install_date, DAY)=30 then a.app_instance_id end) d30 
                             from 
                             (
                             SELECT date(timestamp_micros(user_first_touch_timestamp)) install_date, user_pseudo_id app_instance_id, platform, geo.country,app_info.version version,app_info.id app_id  
                             from `",b[i],".",a,".events_*`
                             where event_name='first_open' and _TABLE_SUFFIX between FORMAT_DATE ('%Y%m%d','",from_date1,"') and FORMAT_DATE ('%Y%m%d','",to_date1,"')) a LEFT JOIN 
                             (select user_pseudo_id app_instance_id,app_info.id app_id,parse_date('%Y%m%d',_table_suffix) date
                             from `",b[i],".",a,".events_*`
                             where _TABLE_SUFFIX between FORMAT_DATE ('%Y%m%d','",from_date1,"') and FORMAT_DATE ('%Y%m%d','",to_date1,"')
                             and event_name in ('user_engagement')
                             group by 1,2,3) b on a.app_id=b.app_id and a.app_instance_id=b.app_instance_id
                             group by 1,2,3,4,5
                             order by 1,2,3,4,5

**Comment by sagishporer** [comment]
Couldn't run the query you sent. I've wrote a query for calculating daily retention which yields results very close to those in the Firebase Console: 
[https://github.com/sagishporer/big-query-queries-for-firebase/wiki/Query:-Daily-retention](https://github.com/sagishporer/big-query-queries-for-firebase/wiki/Query:-Daily-retention)
